### ISSUE TITLE
Balcony outdoor node

### ISSUE THREAD

**Issue by jansauer** [jansauer/home-assistant_config#7]
Idea is to have a ESPHome node with three task areas.

#### 1. Plant monitoring

- [ ] Soil moisture
- [ ] Soil temperature
- [ ] Soil conductivity
- [ ] Water level of the flower box water reservoir
- Pumping water from additional tank

#### 2. Weather Station

- [ ] Air temperature
- [ ] Air humidity
- [ ] Air pressure

  [BME280](https://www.bosch-sensortec.com/bst/products/all_products/bme280) themes to be a good accurate three in one sensor (or BME680?).
  - https://hackaday.com/2017/01/03/humidity-sensor-shootout/
  - http://www.kandrsmith.org/RJS/Misc/hygrometers.html
  - http://www.kandrsmith.org/RJS/Misc/Hygrometers/absolutetemperature.html
  Maybe not buy from Ali in order to get better quality.
  - https://www.reichelt.com/de/de/index.html?ACTION=446&LA=0&q=bme280 

- [ ] Sun sensor

  So far BH1750
  - https://esphome.io/components/sensor/bh1750.html

- [ ] Rain sensor
- precipitation amount
- [ ] Particulate Matter Sensor
  - [x] [SDS011](https://esphome.io/components/sensor/sds011.html)

Not every function makes sense for me as placement is restricted to be between houses and not too far from a wall. Wind direction and speed for example would not be very meaningful.

#### 3. Coziness
Maybe some indirect lights (led strips inside the flower box or to the ground) and a motion sensor.

#### Setup
- [ ] Controller 
   - [x] [ESP32 with WiFi](https://www.aliexpress.com/item//32992390199.html) 
- [ ] some kind of housing
  First idea was some [waterprof clear cover box](https://www.aliexpress.com/item//32961206980.html) but we need some contact to the elements for the sensors to work probably.
  Plastic Electronic Project Box DIY Enclosure Instrument Case; Solar Radiation Shield ?!?
  - https://www.thingiverse.com/thing:713219
  [Jubilee Clips](https://en.wikipedia.org/wiki/Jubilee_Clip)?
- power switch / [slide switch](https://www.aliexpress.com/wholesale?catId=0&initiative_id=SB_20190428122345&SearchText=slide+switch)
- solar power
- webcam for plants, street or doorway
- [ ] ask land lord for permission to attach outdoor antenna (§12)
- [ ] think about calibration
- [ ] send weather data do a online community
  - https://www.wunderground.com/weather/de/hanover/52.384091500000004%2C9.7260433
  - https://openweathermap.org/stations

### Sparks
- https://www.wired.com/2016/04/diy-weather-station/
- https://www.thethingsnetwork.org/forum/t/lora-bme280-environmental-node-with-webbased-backend/9264

**Comment by jansauer** [comment]
https://www.youtube.com/watch?v=G9xdVQii_YY
